#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# What this is: the one-time Firebase console setup for find-my-mate, ticket 02
# in `.scratch/find-my-mate-build/issues/`. Run it from anywhere inside the repo:
#
#     scripts/setup-firebase.sh
#
# Safe to re-run: values already in .env come back as defaults, and .env and
# .firebaserc are rewritten in place rather than appended to. Running it on a
# fresh clone rebuilds the project exactly as `docs/spec.md` §8 describes.

# Run from the repo root, so .env and .firebaserc land where they belong.
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || true)
[[ -n "$REPO_ROOT" ]] || { printf 'Run this from inside the find-my-mate repo.\n'; exit 1; }
cd "$REPO_ROOT"

# _trim strips whitespace, surrounding quotes and trailing commas — repeatedly,
# because a JS snippet line ends in both: `apiKey: "AIza...",`.
_trim() {
  local v="$1" prev
  while :; do
    prev="$v"
    v="${v#"${v%%[![:space:]]*}"}"; v="${v%"${v##*[![:space:]]}"}"
    v="${v#\"}"; v="${v%\"}"; v="${v#\'}"; v="${v%\'}"; v="${v%,}"
    v="${v%"${v##*[![:space:]]}"}"
    [[ "$v" == "$prev" ]] && break
  done
  printf '%s' "$v"
}

TOTAL_STAGES=7

banner "Firebase project for Find My Mate"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create the project"
say "One Firebase project for the whole family: Firestore + anonymous sign-in, on the free Spark plan."
open_url "https://console.firebase.google.com/"
step "Click 'Create a project' (or 'Add project')."
step "Project name: find-my-mate. A numeric suffix on the project id is fine."
step "Google Analytics: turn it OFF — this app needs none."
step "If it asks for a location for Google Cloud resources, choose australia-southeast1 (Sydney)."
step "Click 'Create project', wait for it to finish, then 'Continue'."
pause "Project created? Press Enter."
say "Now copy the project id from the console URL bar — it sits between /project/ and /overview."
note "  https://console.firebase.google.com/project/find-my-mate-1a2b3/overview"
ask FIREBASE_PROJECT_ID "Paste the project id:"
FIREBASE_PROJECT_ID=$(_trim "$FIREBASE_PROJECT_ID")
[[ -n "$FIREBASE_PROJECT_ID" ]] || { warn "empty project id; re-run this stage"; exit 1; }
write_env FIREBASE_PROJECT_ID "$FIREBASE_PROJECT_ID"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Add a second owner"
say "Two people must be able to administer this project — one lost Google account must not strand the family's data."
open_url "https://console.firebase.google.com/project/$FIREBASE_PROJECT_ID/settings/iam"
step "Click 'Add member'."
step "Type the other adult's Google account email."
step "Set the role to 'Owner' (the plain Owner role, not Viewer or Editor)."
step "Click 'Add'. They can now sign in at console.firebase.google.com with that account."
ask FIREBASE_SECOND_OWNER_EMAIL "Paste the email you added, so it's on record:"
FIREBASE_SECOND_OWNER_EMAIL=$(_trim "$FIREBASE_SECOND_OWNER_EMAIL")
write_env FIREBASE_SECOND_OWNER_EMAIL "$FIREBASE_SECOND_OWNER_EMAIL"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Turn on anonymous sign-in"
say "A Member is an app install, so the app signs in anonymously: no email, no password, no user-visible account."
open_url "https://console.firebase.google.com/project/$FIREBASE_PROJECT_ID/authentication/providers"
step "If Authentication isn't set up yet, click 'Get started'."
step "On the 'Sign-in method' tab, click 'Anonymous' in the list of providers."
step "Toggle it to 'Enable' and click 'Save'."
pause "Anonymous shows as Enabled? Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create Firestore in Sydney"
say "The database itself — empty for now. Ticket 03 deploys the security rules that become the trust boundary."
warn "The location is permanent: Firestore cannot be moved afterwards, only deleted and recreated."
open_url "https://console.firebase.google.com/project/$FIREBASE_PROJECT_ID/firestore"
step "Click 'Create database'."
step "Edition: 'Standard edition' (Enterprise is a paid, MongoDB-compatible edition — not this app)."
step "Location: australia-southeast1 (Sydney). If the location is already fixed to anything else, stop here and say so."
step "If it offers a security-rules choice, pick 'Production mode' (locked). The rules arrive in ticket 03; until then everything is denied, which is what we want."
step "Click 'Create' and wait for the database to finish provisioning."
if confirm "Is the database created, in australia-southeast1 (Sydney)?"; then
  say "Good — the location is fixed for good, so that was the one irreversible click of this wizard."
else
  warn "That location is permanent, so the database has to be deleted and created again in Sydney."
  step "In the console: select the database > 'Delete database' > Create database > australia-southeast1."
  pause "Recreated in Sydney? Press Enter (Ctrl-C to stop and re-run this wizard later)."
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Register the web app and copy firebaseConfig"
say "The app uses the Firebase JS SDK, and that config comes from a registered web app."
say "No google-services.json or GoogleService-Info.plist: Expo Go runs the JS SDK, which needs neither."
open_url "https://console.firebase.google.com/project/$FIREBASE_PROJECT_ID/settings/general"
step "Scroll to 'Your apps' and click the web icon (</>)."
step "App nickname: find-my-mate. Leave 'Also set up Firebase Hosting' unchecked."
step "Click 'Register app' (skip the Analytics offer)."
step "The console now shows a firebaseConfig block. Copy each value it lists, on its own."
note "The apiKey is not a secret here: it is public by design and the security rules are what protect the data."
ask FIREBASE_API_KEY "apiKey (starts with AIza):"
ask FIREBASE_AUTH_DOMAIN "authDomain (ends .firebaseapp.com):"
ask FIREBASE_STORAGE_BUCKET "storageBucket (...appspot.com or ...firebasestorage.app):"
ask FIREBASE_MESSAGING_SENDER_ID "messagingSenderId (digits only):"
ask FIREBASE_APP_ID "appId (starts with 1:):"
FIREBASE_API_KEY=$(_trim "$FIREBASE_API_KEY")
FIREBASE_AUTH_DOMAIN=$(_trim "$FIREBASE_AUTH_DOMAIN")
FIREBASE_STORAGE_BUCKET=$(_trim "$FIREBASE_STORAGE_BUCKET")
FIREBASE_MESSAGING_SENDER_ID=$(_trim "$FIREBASE_MESSAGING_SENDER_ID")
FIREBASE_APP_ID=$(_trim "$FIREBASE_APP_ID")
[[ "$FIREBASE_API_KEY" == AIza* ]] || warn "that apiKey doesn't look like an AIza... key; check the line you copied"
[[ "$FIREBASE_APP_ID" == *:* ]] || warn "that appId doesn't look like 1:1234:web:abcd; check the line you copied"
write_env FIREBASE_API_KEY "$FIREBASE_API_KEY"
write_env FIREBASE_AUTH_DOMAIN "$FIREBASE_AUTH_DOMAIN"
write_env FIREBASE_STORAGE_BUCKET "$FIREBASE_STORAGE_BUCKET"
write_env FIREBASE_MESSAGING_SENDER_ID "$FIREBASE_MESSAGING_SENDER_ID"
write_env FIREBASE_APP_ID "$FIREBASE_APP_ID"
note "Ticket 04 will copy these into src/firebase.ts, where they get committed."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify Spark, and no App Check"
say "Two of this ticket's criteria are things you do NOT click. Check both now."
open_url "https://console.firebase.google.com/project/$FIREBASE_PROJECT_ID"
step "Gear icon (top left) > 'Usage and billing' > 'Details & settings': the plan should read 'Spark'."
step "Do not accept any upgrade offer — v1 is Spark-only by design, so no Cloud Functions and no Blaze."
step "Then in the left nav: Build > App Check. It should still show its intro screen, i.e. nothing registered."
step "Leave App Check alone: it cannot attest Expo Go, so security rules are the boundary (spec section 8)."
pause "Spark, no Functions, no App Check? Press Enter."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Sign this machine into the Firebase CLI"
say "Ticket 03 deploys the rules with the Firebase CLI, which needs a one-time browser sign-in."
note "The first run downloads firebase-tools, so give it a minute."
step "The command below prints a sign-in URL; in WSL your browser may not open by itself, so copy it if needed."
step "Sign in with the Google account that owns the project, then come back here."
npx --yes firebase-tools@latest login || warn "login didn't finish; re-run this stage when you're ready"
pause "Signed in? Press Enter and we'll check."
if npx --yes firebase-tools@latest projects:list 2>/dev/null | grep -q "$FIREBASE_PROJECT_ID"; then
  say "✓ the CLI can see $FIREBASE_PROJECT_ID"
else
  warn "the CLI didn't list $FIREBASE_PROJECT_ID — check you signed in with the owning account"
fi
printf '{\n  "projects": {\n    "default": "%s"\n  }\n}\n' "$FIREBASE_PROJECT_ID" > .firebaserc
say "wrote .firebaserc, so the CLI commands in ticket 03 need no --project flag"
# ──────────────────────────────────────────────────────────────────────────

finish
